export const allItemNames = 
["Observer Ward",
"Clarity",
"Smoke of Deceit",
"Enchanted Mango",
"Faerie Fire",
"Sentry Ward",
"Tome of Knowledge",
"Dust of Appearance",
"Tango",
"Town Portal Scroll",
"Healing Salve",
"Bottle",
"Aghanim's Shard",
"Iron Branch",
"Gauntlets of Strength",
"Mantle of Intelligence",
"Slippers of Agility",
"Circlet",
"Band of Elvenskin",
"Belt of Strength",
"Crown",
"Robe of the Magi",
"Blade of Alacrity",
"Ogre Axe",
"Staff of Wizardry",
"Quelling Blade",
"Ring of Protection",
"Infused Raindrops",
"Orb of Venom",
"Blight Stone",
"Blades of Attack",
"Gloves of Haste",
"Chainmail",
"Quarterstaff",
"Helm of Iron Will",
"Blitz Knuckles",
"Broadsword",
"Javelin",
"Claymore",
"Mithril Hammer",
"Ring of Regen",
"Sage's Mask",
"Magic Stick",
"Fluffy Hat",
"Wind Lace",
"Boots of Speed",
"Cloak",
"Voodoo Mask",
"Gem of True Sight",
"Morbid Mask",
"Shadow Amulet",
"Ghost Scepter",
"Blink Dagger",
"Ring of Health",
"Void Stone",
"Energy Booster",
"Vitality Booster",
"Point Booster",
"Platemail",
"Talisman of Evasion",
"Hyperstone",
"Ultimate Orb",
"Demon Edge",
"Eaglesong",
"Mystic Staff",
"Reaver",
"Sacred Relic",
"Magic Wand",
"Bracer",
"Null Talisman",
"Wraith Band",
"Soul Ring",
"Orb of Corrosion",
"Falcon Blade",
"Power Treads",
"Oblivion Staff",
"Phase Boots",
"Perseverance",
"Mask of Madness",
"Hand of Midas",
"Helm of the Dominator",
"Helm of the Dominator 1",
"Boots of Travel",
"Moon Shard",
"Buckler",
"Headdress",
"Ring of Basilius",
"Urn of Shadows",
"Tranquil Boots",
"Medallion of Courage",
"Arcane Boots",
"Drum of Endurance",
"Mekansm",
"Holy Locket",
"Vladmir's Offering",
"Spirit Vessel",
"Pipe of Insight",
"Guardian Greaves",
"Veil of Discord",
"Glimmer Cape",
"Necronomicon",
"Force Staff",
"Aether Lens",
"Witch Blade",
"Eul's Scepter of Divinity",
"Dagon",
"Rod of Atos",
"Orchid Malevolence",
"Solar Crest",
"Aghanim's Scepter",
"Refresher Orb",
"Octarine Core",
"Scythe of Vyse",
"Aghanim's Blessing",
"Gleipnir",
"Wind Waker",
"Hood of Defiance",
"Vanguard",
"Blade Mail",
"Aeon Disk",
"Soul Booster",
"Eternal Shroud",
"Crimson Guard",
"Lotus Orb",
"Black King Bar",
"Hurricane Pike",
"Linken's Sphere",
"Manta Style",
"Heart of Tarrasque",
"Shiva's Guard",
"Assault Cuirass",
"Bloodstone",
"Crystalys",
"Meteor Hammer",
"Armlet of Mordiggian",
"Skull Basher",
"Shadow Blade",
"Desolator",
"Battle Fury",
"Ethereal Blade",
"Nullifier",
"Monkey King Bar",
"Butterfly",
"Daedalus",
"Radiance",
"Silver Edge",
"Divine Rapier",
"Bloodthorn",
"Abyssal Blade",
"Dragon Lance",
"Kaya",
"Sange",
"Yasha",
"Echo Sabre",
"Maelstrom",
"Diffusal Blade",
"Mage Slayer",
"Heaven's Halberd",
"Kaya and Sange",
"Sange and Yasha",
"Yasha and Kaya",
"Satanic",
"Eye of Skadi",
"Mjollnir",
"Arcane Blink",
"Overwhelming Blink",
"Swift Blink"]


